CREATE DATABASE IF NOT EXISTS kawak
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kawak;

-- Types
CREATE TABLE TIP_TIPO_DOC (
  TIP_ID INT AUTO_INCREMENT PRIMARY KEY,
  TIP_NOMBRE VARCHAR(60) NOT NULL,
  TIP_PREFIJO VARCHAR(20) NOT NULL
) ENGINE=InnoDB;

-- Processes
CREATE TABLE PRO_PROCESO (
  PRO_ID INT AUTO_INCREMENT PRIMARY KEY,
  PRO_PREFIJO VARCHAR(20) NOT NULL,
  PRO_NOMBRE VARCHAR(60) NOT NULL
) ENGINE=InnoDB;

-- Documents
CREATE TABLE DOC_DOCUMENTO (
  DOC_ID INT AUTO_INCREMENT PRIMARY KEY,
  DOC_NOMBRE VARCHAR(60) NOT NULL,
  DOC_CODIGO INT NOT NULL,
  DOC_CONTENIDO VARCHAR(4000) NULL,
  DOC_ID_TIPO INT NOT NULL,
  DOC_ID_PROCESO INT NOT NULL,
  INDEX DOC_TIPO_idx (DOC_ID_TIPO),
  INDEX DOC_PROCESO_idx (DOC_ID_PROCESO),
  CONSTRAINT fk_doc_tipo    FOREIGN KEY (DOC_ID_TIPO)    REFERENCES TIP_TIPO_DOC(TIP_ID),
  CONSTRAINT fk_doc_proceso FOREIGN KEY (DOC_ID_PROCESO) REFERENCES PRO_PROCESO(PRO_ID)
) ENGINE=InnoDB;

ALTER TABLE DOC_DOCUMENTO
  ADD UNIQUE KEY u_tripleta (DOC_ID_TIPO, DOC_ID_PROCESO, DOC_CODIGO);
