INSERT INTO TIP_TIPO_DOC (TIP_NOMBRE, TIP_PREFIJO) VALUES
('Política','POL'),('Procedimiento','PRO'),('Instructivo','INS'),('Formato','FOR'),('Plan','PLA');

INSERT INTO PRO_PROCESO (PRO_PREFIJO, PRO_NOMBRE) VALUES
('CAL','Calidad'),('SEG','Seguridad'),('OPE','Operaciones'),('FIN','Finanzas'),('RRH','RRHH');

CREATE OR REPLACE VIEW VW_DOC_DOCUMENTO AS
SELECT
  d.DOC_ID,
  d.DOC_NOMBRE,
  CONCAT(t.TIP_PREFIJO,'-',p.PRO_PREFIJO,'-',d.DOC_CODIGO) AS CODIGO,
  d.DOC_CODIGO,
  d.DOC_CONTENIDO,
  d.DOC_ID_TIPO,
  d.DOC_ID_PROCESO
FROM DOC_DOCUMENTO d
JOIN TIP_TIPO_DOC t ON t.TIP_ID = d.DOC_ID_TIPO
JOIN PRO_PROCESO  p ON p.PRO_ID = d.DOC_ID_PROCESO;
